name: Nginx Config Check

on:
  pull_request:
    branches:
      - main

jobs:
  test-config:
    runs-on: ubuntu-latest
    steps:
      - name: Download the repository
        uses: actions/checkout@v4

      - name: Check if config contains a listen port
        run: |
          echo "Starting the test..."
          grep "listen" nginx.conf
          echo "Test passed: A port is configured."
